baseURL = "https://example.com"
locale = 'en-us'
title = "Soheil's Block"
theme = "etch"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "Soheil's Block"
  copyright = "Copyright © 2026 Soheil"
  dark = "auto"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'
